<?php

namespace EHXDonate\Helpers;

/**
 * Countries
 *
 * Returns an array of countries and codes.
 *
 * @author      WooThemes
 * @category    i18n
 * @package     payform/i18n
 * @version     2.5.0
 */

if (!defined('ABSPATH')) {
    exit;
}

class Country
{
    public static function getAll()
    {
        $country_names = array(
            'AF' => __('Afghanistan', 'fluent-raise'),
            'AX' => __('Åland Islands', 'fluent-raise'),
            'AL' => __('Albania', 'fluent-raise'),
            'DZ' => __('Algeria', 'fluent-raise'),
            'AS' => __('American Samoa', 'fluent-raise'),
            'AD' => __('Andorra', 'fluent-raise'),
            'AO' => __('Angola', 'fluent-raise'),
            'AI' => __('Anguilla', 'fluent-raise'),
            'AQ' => __('Antarctica', 'fluent-raise'),
            'AG' => __('Antigua and Barbuda', 'fluent-raise'),
            'AR' => __('Argentina', 'fluent-raise'),
            'AM' => __('Armenia', 'fluent-raise'),
            'AW' => __('Aruba', 'fluent-raise'),
            'AU' => __('Australia', 'fluent-raise'),
            'AT' => __('Austria', 'fluent-raise'),
            'AZ' => __('Azerbaijan', 'fluent-raise'),
            'BS' => __('Bahamas', 'fluent-raise'),
            'BH' => __('Bahrain', 'fluent-raise'),
            'BD' => __('Bangladesh', 'fluent-raise'),
            'BB' => __('Barbados', 'fluent-raise'),
            'BY' => __('Belarus', 'fluent-raise'),
            'BE' => __('Belgium', 'fluent-raise'),
            'PW' => __('Belau', 'fluent-raise'),
            'BZ' => __('Belize', 'fluent-raise'),
            'BJ' => __('Benin', 'fluent-raise'),
            'BM' => __('Bermuda', 'fluent-raise'),
            'BT' => __('Bhutan', 'fluent-raise'),
            'BO' => __('Bolivia', 'fluent-raise'),
            'BQ' => __('Bonaire, Saint Eustatius and Saba', 'fluent-raise'),
            'BA' => __('Bosnia and Herzegovina', 'fluent-raise'),
            'BW' => __('Botswana', 'fluent-raise'),
            'BV' => __('Bouvet Island', 'fluent-raise'),
            'BR' => __('Brazil', 'fluent-raise'),
            'IO' => __('British Indian Ocean Territory', 'fluent-raise'),
            'VG' => __('British Virgin Islands', 'fluent-raise'),
            'BN' => __('Brunei', 'fluent-raise'),
            'BG' => __('Bulgaria', 'fluent-raise'),
            'BF' => __('Burkina Faso', 'fluent-raise'),
            'BI' => __('Burundi', 'fluent-raise'),
            'KH' => __('Cambodia', 'fluent-raise'),
            'CM' => __('Cameroon', 'fluent-raise'),
            'CA' => __('Canada', 'fluent-raise'),
            'CV' => __('Cape Verde', 'fluent-raise'),
            'KY' => __('Cayman Islands', 'fluent-raise'),
            'CF' => __('Central African Republic', 'fluent-raise'),
            'TD' => __('Chad', 'fluent-raise'),
            'CL' => __('Chile', 'fluent-raise'),
            'CN' => __('China', 'fluent-raise'),
            'CX' => __('Christmas Island', 'fluent-raise'),
            'CC' => __('Cocos (Keeling) Islands', 'fluent-raise'),
            'CO' => __('Colombia', 'fluent-raise'),
            'KM' => __('Comoros', 'fluent-raise'),
            'CG' => __('Congo (Brazzaville)', 'fluent-raise'),
            'CD' => __('Congo (Kinshasa)', 'fluent-raise'),
            'CK' => __('Cook Islands', 'fluent-raise'),
            'CR' => __('Costa Rica', 'fluent-raise'),
            'HR' => __('Croatia', 'fluent-raise'),
            'CU' => __('Cuba', 'fluent-raise'),
            'CW' => __('Cura&ccedil;ao', 'fluent-raise'),
            'CY' => __('Cyprus', 'fluent-raise'),
            'CZ' => __('Czech Republic', 'fluent-raise'),
            'DK' => __('Denmark', 'fluent-raise'),
            'DJ' => __('Djibouti', 'fluent-raise'),
            'DM' => __('Dominica', 'fluent-raise'),
            'DO' => __('Dominican Republic', 'fluent-raise'),
            'EC' => __('Ecuador', 'fluent-raise'),
            'EG' => __('Egypt', 'fluent-raise'),
            'SV' => __('El Salvador', 'fluent-raise'),
            'GQ' => __('Equatorial Guinea', 'fluent-raise'),
            'ER' => __('Eritrea', 'fluent-raise'),
            'EE' => __('Estonia', 'fluent-raise'),
            'ET' => __('Ethiopia', 'fluent-raise'),
            'FK' => __('Falkland Islands', 'fluent-raise'),
            'FO' => __('Faroe Islands', 'fluent-raise'),
            'FJ' => __('Fiji', 'fluent-raise'),
            'FI' => __('Finland', 'fluent-raise'),
            'FR' => __('France', 'fluent-raise'),
            'GF' => __('French Guiana', 'fluent-raise'),
            'PF' => __('French Polynesia', 'fluent-raise'),
            'TF' => __('French Southern Territories', 'fluent-raise'),
            'GA' => __('Gabon', 'fluent-raise'),
            'GM' => __('Gambia', 'fluent-raise'),
            'GE' => __('Georgia', 'fluent-raise'),
            'DE' => __('Germany', 'fluent-raise'),
            'GH' => __('Ghana', 'fluent-raise'),
            'GI' => __('Gibraltar', 'fluent-raise'),
            'GR' => __('Greece', 'fluent-raise'),
            'GL' => __('Greenland', 'fluent-raise'),
            'GD' => __('Grenada', 'fluent-raise'),
            'GP' => __('Guadeloupe', 'fluent-raise'),
            'GU' => __('Guam', 'fluent-raise'),
            'GT' => __('Guatemala', 'fluent-raise'),
            'GG' => __('Guernsey', 'fluent-raise'),
            'GN' => __('Guinea', 'fluent-raise'),
            'GW' => __('Guinea-Bissau', 'fluent-raise'),
            'GY' => __('Guyana', 'fluent-raise'),
            'HT' => __('Haiti', 'fluent-raise'),
            'HM' => __('Heard Island and McDonald Islands', 'fluent-raise'),
            'HN' => __('Honduras', 'fluent-raise'),
            'HK' => __('Hong Kong', 'fluent-raise'),
            'HU' => __('Hungary', 'fluent-raise'),
            'IS' => __('Iceland', 'fluent-raise'),
            'IN' => __('India', 'fluent-raise'),
            'ID' => __('Indonesia', 'fluent-raise'),
            'IR' => __('Iran', 'fluent-raise'),
            'IQ' => __('Iraq', 'fluent-raise'),
            'IE' => __('Ireland', 'fluent-raise'),
            'IM' => __('Isle of Man', 'fluent-raise'),
            'IL' => __('Israel', 'fluent-raise'),
            'IT' => __('Italy', 'fluent-raise'),
            'CI' => __('Ivory Coast', 'fluent-raise'),
            'JM' => __('Jamaica', 'fluent-raise'),
            'JP' => __('Japan', 'fluent-raise'),
            'JE' => __('Jersey', 'fluent-raise'),
            'JO' => __('Jordan', 'fluent-raise'),
            'KZ' => __('Kazakhstan', 'fluent-raise'),
            'KE' => __('Kenya', 'fluent-raise'),
            'KI' => __('Kiribati', 'fluent-raise'),
            'KW' => __('Kuwait', 'fluent-raise'),
            'KG' => __('Kyrgyzstan', 'fluent-raise'),
            'LA' => __('Laos', 'fluent-raise'),
            'LV' => __('Latvia', 'fluent-raise'),
            'LB' => __('Lebanon', 'fluent-raise'),
            'LS' => __('Lesotho', 'fluent-raise'),
            'LR' => __('Liberia', 'fluent-raise'),
            'LY' => __('Libya', 'fluent-raise'),
            'LI' => __('Liechtenstein', 'fluent-raise'),
            'LT' => __('Lithuania', 'fluent-raise'),
            'LU' => __('Luxembourg', 'fluent-raise'),
            'MO' => __('Macao S.A.R., China', 'fluent-raise'),
            'MK' => __('Macedonia', 'fluent-raise'),
            'MG' => __('Madagascar', 'fluent-raise'),
            'MW' => __('Malawi', 'fluent-raise'),
            'MY' => __('Malaysia', 'fluent-raise'),
            'MV' => __('Maldives', 'fluent-raise'),
            'ML' => __('Mali', 'fluent-raise'),
            'MT' => __('Malta', 'fluent-raise'),
            'MH' => __('Marshall Islands', 'fluent-raise'),
            'MQ' => __('Martinique', 'fluent-raise'),
            'MR' => __('Mauritania', 'fluent-raise'),
            'MU' => __('Mauritius', 'fluent-raise'),
            'YT' => __('Mayotte', 'fluent-raise'),
            'MX' => __('Mexico', 'fluent-raise'),
            'FM' => __('Micronesia', 'fluent-raise'),
            'MD' => __('Moldova', 'fluent-raise'),
            'MC' => __('Monaco', 'fluent-raise'),
            'MN' => __('Mongolia', 'fluent-raise'),
            'ME' => __('Montenegro', 'fluent-raise'),
            'MS' => __('Montserrat', 'fluent-raise'),
            'MA' => __('Morocco', 'fluent-raise'),
            'MZ' => __('Mozambique', 'fluent-raise'),
            'MM' => __('Myanmar', 'fluent-raise'),
            'NA' => __('Namibia', 'fluent-raise'),
            'NR' => __('Nauru', 'fluent-raise'),
            'NP' => __('Nepal', 'fluent-raise'),
            'NL' => __('Netherlands', 'fluent-raise'),
            'NC' => __('New Caledonia', 'fluent-raise'),
            'NZ' => __('New Zealand', 'fluent-raise'),
            'NI' => __('Nicaragua', 'fluent-raise'),
            'NE' => __('Niger', 'fluent-raise'),
            'NG' => __('Nigeria', 'fluent-raise'),
            'NU' => __('Niue', 'fluent-raise'),
            'NF' => __('Norfolk Island', 'fluent-raise'),
            'MP' => __('Northern Mariana Islands', 'fluent-raise'),
            'KP' => __('North Korea', 'fluent-raise'),
            'NO' => __('Norway', 'fluent-raise'),
            'OM' => __('Oman', 'fluent-raise'),
            'PK' => __('Pakistan', 'fluent-raise'),
            'PS' => __('Palestinian Territory', 'fluent-raise'),
            'PA' => __('Panama', 'fluent-raise'),
            'PG' => __('Papua New Guinea', 'fluent-raise'),
            'PY' => __('Paraguay', 'fluent-raise'),
            'PE' => __('Peru', 'fluent-raise'),
            'PH' => __('Philippines', 'fluent-raise'),
            'PN' => __('Pitcairn', 'fluent-raise'),
            'PL' => __('Poland', 'fluent-raise'),
            'PT' => __('Portugal', 'fluent-raise'),
            'PR' => __('Puerto Rico', 'fluent-raise'),
            'QA' => __('Qatar', 'fluent-raise'),
            'RE' => __('Reunion', 'fluent-raise'),
            'RO' => __('Romania', 'fluent-raise'),
            'RU' => __('Russia', 'fluent-raise'),
            'RW' => __('Rwanda', 'fluent-raise'),
            'BL' => __('Saint Barth&eacute;lemy', 'fluent-raise'),
            'SH' => __('Saint Helena', 'fluent-raise'),
            'KN' => __('Saint Kitts and Nevis', 'fluent-raise'),
            'LC' => __('Saint Lucia', 'fluent-raise'),
            'MF' => __('Saint Martin (French part)', 'fluent-raise'),
            'SX' => __('Saint Martin (Dutch part)', 'fluent-raise'),
            'PM' => __('Saint Pierre and Miquelon', 'fluent-raise'),
            'VC' => __('Saint Vincent and the Grenadines', 'fluent-raise'),
            'SM' => __('San Marino', 'fluent-raise'),
            'ST' => __('S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'fluent-raise'),
            'SA' => __('Saudi Arabia', 'fluent-raise'),
            'SN' => __('Senegal', 'fluent-raise'),
            'RS' => __('Serbia', 'fluent-raise'),
            'SC' => __('Seychelles', 'fluent-raise'),
            'SL' => __('Sierra Leone', 'fluent-raise'),
            'SG' => __('Singapore', 'fluent-raise'),
            'SK' => __('Slovakia', 'fluent-raise'),
            'SI' => __('Slovenia', 'fluent-raise'),
            'SB' => __('Solomon Islands', 'fluent-raise'),
            'SO' => __('Somalia', 'fluent-raise'),
            'ZA' => __('South Africa', 'fluent-raise'),
            'GS' => __('South Georgia/Sandwich Islands', 'fluent-raise'),
            'KR' => __('South Korea', 'fluent-raise'),
            'SS' => __('South Sudan', 'fluent-raise'),
            'ES' => __('Spain', 'fluent-raise'),
            'LK' => __('Sri Lanka', 'fluent-raise'),
            'SD' => __('Sudan', 'fluent-raise'),
            'SR' => __('Suriname', 'fluent-raise'),
            'SJ' => __('Svalbard and Jan Mayen', 'fluent-raise'),
            'SZ' => __('Swaziland', 'fluent-raise'),
            'SE' => __('Sweden', 'fluent-raise'),
            'CH' => __('Switzerland', 'fluent-raise'),
            'SY' => __('Syria', 'fluent-raise'),
            'TW' => __('Taiwan', 'fluent-raise'),
            'TJ' => __('Tajikistan', 'fluent-raise'),
            'TZ' => __('Tanzania', 'fluent-raise'),
            'TH' => __('Thailand', 'fluent-raise'),
            'TL' => __('Timor-Leste', 'fluent-raise'),
            'TG' => __('Togo', 'fluent-raise'),
            'TK' => __('Tokelau', 'fluent-raise'),
            'TO' => __('Tonga', 'fluent-raise'),
            'TT' => __('Trinidad and Tobago', 'fluent-raise'),
            'TN' => __('Tunisia', 'fluent-raise'),
            'TR' => __('Turkey', 'fluent-raise'),
            'TM' => __('Turkmenistan', 'fluent-raise'),
            'TC' => __('Turks and Caicos Islands', 'fluent-raise'),
            'TV' => __('Tuvalu', 'fluent-raise'),
            'UG' => __('Uganda', 'fluent-raise'),
            'UA' => __('Ukraine', 'fluent-raise'),
            'AE' => __('United Arab Emirates', 'fluent-raise'),
            'GB' => __('United Kingdom (UK)', 'fluent-raise'),
            'US' => __('United States (US)', 'fluent-raise'),
            'UM' => __('United States (US) Minor Outlying Islands', 'fluent-raise'),
            'VI' => __('United States (US) Virgin Islands', 'fluent-raise'),
            'UY' => __('Uruguay', 'fluent-raise'),
            'UZ' => __('Uzbekistan', 'fluent-raise'),
            'VU' => __('Vanuatu', 'fluent-raise'),
            'VA' => __('Vatican', 'fluent-raise'),
            'VE' => __('Venezuela', 'fluent-raise'),
            'VN' => __('Vietnam', 'fluent-raise'),
            'WF' => __('Wallis and Futuna', 'fluent-raise'),
            'EH' => __('Western Sahara', 'fluent-raise'),
            'WS' => __('Samoa', 'fluent-raise'),
            'YE' => __('Yemen', 'fluent-raise'),
            'ZM' => __('Zambia', 'fluent-raise'),
            'ZW' => __('Zimbabwe', 'fluent-raise'),
        );

        return apply_filters('payform_editor_countries', $country_names);
    }

    public static function languageCodes()
    {
        return $langCodes = array(
            'AF' => 'fa-AF',
            'AL' => 'sq-AL',
            'DZ' => 'ar-DZ',
            'AS' => 'sm-AS',
            'AD' => 'ca-AD',
            'AO' => 'pt-AO',
            'AR' => 'es-AR',
            'AM' => 'hy-AM',
            'AU' => 'en-AU',
            'AT' => 'de-AT',
            'AZ' => 'az-AZ',
            'BH' => 'ar-BH',
            'BD' => 'bn-BD',
            'BY' => 'be-BY',
            'BE' => 'nl-BE',
            'BZ' => 'en-BZ',
            'BJ' => 'fr-BJ',
            'BT' => 'dz-BT',
            'BO' => 'es-BO',
            'BA' => 'bs-BA',
            'BW' => 'en-BW',
            'BR' => 'pt-BR',
            'BN' => 'ms-BN',
            'BG' => 'bg-BG',
            'BF' => 'fr-BF',
            'BI' => 'fr-BI',
            'KH' => 'km-KH',
            'CM' => 'en-CM',
            'CA' => 'en-CA',
            'CV' => 'pt-CV',
            'CF' => 'fr-CF',
            'TD' => 'fr-TD',
            'CL' => 'es-CL',
            'CN' => 'zh-CN',
            'CO' => 'es-CO',
            'KM' => 'ar-KM',
            'CD' => 'fr-CD',
            'CG' => 'fr-CG',
            'CR' => 'es-CR',
            'CI' => 'fr-CI',
            'HR' => 'hr-HR',
            'CU' => 'es-CU',
            'CY' => 'el-CY',
            'CZ' => 'cs-CZ',
            'DK' => 'da-DK',
            'DJ' => 'fr-DJ',
            'DM' => 'en-DM',
            'DO' => 'es-DO',
            'EC' => 'es-EC',
            'EG' => 'ar-EG',
            'SV' => 'es-SV',
            'GQ' => 'es-GQ',
            'ER' => 'ti-ER',
            'EE' => 'et-EE',
            'ET' => 'am-ET',
            'FJ' => 'en-FJ',
            'FI' => 'fi-FI',
            'FR' => 'fr-FR',
            'GA' => 'fr-GA',
            'GM' => 'en-GM',
            'GE' => 'ka-GE',
            'DE' => 'de-DE',
            'GH' => 'en-GH',
            'GR' => 'el-GR',
            'GD' => 'en-GD',
            'GT' => 'es-GT',
            'GN' => 'fr-GN',
            'GW' => 'pt-GW',
            'GY' => 'en-GY',
            'HT' => 'fr-HT',
            'HN' => 'es-HN',
            'HU' => 'hu-HU',
            'IS' => 'is-IS',
            'IN' => 'hi-IN',
            'ID' => 'id-ID',
            'IR' => 'fa-IR',
            'IQ' => 'ar-IQ',
            'IE' => 'en-IE',
            'IL' => 'he-IL',
            'IT' => 'it-IT',
            'JM' => 'en-JM',
            'JP' => 'ja-JP',
            'JO' => 'ar-JO',
            'KZ' => 'kk-KZ',
            'KE' => 'sw-KE',
            'KI' => 'en-KI',
            'KR' => 'ko-KR',
            'KW' => 'ar-KW',
            'KG' => 'ky-KG',
            'LA' => 'lo-LA',
            'LV' => 'lv-LV',
            'LB' => 'ar-LB',
            'LS' => 'en-LS',
            'LR' => 'en-LR',
            'LY' => 'ar-LY',
            'LI' => 'de-LI',
            'LT' => 'lt-LT',
            'LU' => 'lb-LU',
            'MG' => 'mg-MG',
            'MW' => 'en-MW',
            'MY' => 'ms-MY',
            'MV' => 'dv-MV',
            'ML' => 'fr-ML',
            'MT' => 'mt-MT',
            'MH' => 'mh-MH',
            'MR' => 'ar-MR',
            'MU' => 'mfe-MU',
            'MX' => 'es-MX',
            'FM' => 'en-FM',
            'MD' => 'ro-MD',
            'MC' => 'fr-MC',
            'MN' => 'mn-MN',
            'ME' => 'sr-ME',
            'MA' => 'ar-MA',
            'MZ' => 'pt-MZ',
            'NA' => 'en-NA',
            'NR' => 'en-NR',
            'NP' => 'ne-NP',
            'NL' => 'nl-NL',
            'NZ' => 'en-NZ',
            'NI' => 'es-NI',
            'NG' => 'en-NG',
            'NO' => 'no-NO',
            'OM' => 'ar-OM',
            'PK' => 'ur-PK',
            'PW' => 'en-PW',
            'PA' => 'es-PA',
            'PG' => 'en-PG',
            'PY' => 'es-PY',
            'PE' => 'es-PE',
            'PH' => 'en-PH',
            'PL' => 'pl-PL',
            'PT' => 'pt-PT',
            'QA' => 'ar-QA',
            'RO' => 'ro-RO',
            'RU' => 'ru-RU',
            'RW' => 'rw-RW',
            'WS' => 'sm-WS',
            'SM' => 'it-SM',
            'SA' => 'ar-SA',
            'SN' => 'fr-SN',
            'RS' => 'sr-RS',
            'SC' => 'fr-SC',
            'SL' => 'en-SL',
            'SG' => 'en-SG', 
            'SK' => 'sk-SK',
            'SI' => 'sl-SI',
            'SB' => 'en-SB',
            'SO' => 'so-SO',
            'ZA' => 'en-ZA',
            'ES' => 'es-ES',
            'LK' => 'si-LK', 
            'SD' => 'ar-SD',
            'SR' => 'nl-SR',
            'SZ' => 'en-SZ', 
            'SE' => 'sv-SE',
            'CH' => 'de-CH', 
            'SY' => 'ar-SY',
            'TW' => 'zh-TW',
            'TJ' => 'tg-TJ',
            'TZ' => 'sw-TZ',
            'TH' => 'th-TH',
            'TL' => 'pt-TL',
            'TG' => 'fr-TG',
            'TO' => 'to-TO',
            'TT' => 'en-TT',
            'TN' => 'ar-TN',
            'TR' => 'tr-TR',
            'TM' => 'tk-TM',
            'TV' => 'en-TV',
            'UG' => 'en-UG',
            'UA' => 'uk-UA',
            'AE' => 'ar-AE',
            'GB' => 'en-GB',
            'US' => 'en-US',
            'UY' => 'es-UY',
            'UZ' => 'uz-UZ', 
            'VU' => 'bi-VU', 
            'VE' => 'es-VE',
            'VN' => 'vi-VN',
            'YE' => 'ar-YE',
            'ZM' => 'en-ZM',
            'ZW' => 'en-ZW',
        );
    }

    public static function getLanguageCodeByCountryCode($country)
    {
        $langCodes = self::languageCodes();
        return $langCodes[$country] ? $langCodes[$country] : '';
    
    }

    public static function getCountryCode($country_name)
    {
        $countries = self::getAll();
        $country_code = array_search($country_name, $countries);
        return $country_code ? $country_code : '';
    }

    public static function getCountryName($country_code)
    {
        $countries = self::getAll();
        return $countries[$country_code] ? $countries[$country_code] : '';
    }
}