<?php

namespace EHXDonate\Helpers;

class Currency
{
    public static function getAll()
    {
        $currencies = [
            'AED' => 'United Arab Emirates Dirham',
            'AFN' => 'Afghan Afghani',
            'ALL' => 'Albanian Lek',
            'AMD' => 'Armenian Dram',
            'ANG' => 'Netherlands Antillean Gulden',
            'AOA' => 'Angolan Kwanza',
            'ARS' => 'Argentine Peso', // non amex
            'AUD' => 'Australian Dollar',
            'AWG' => 'Aruban Florin',
            'AZN' => 'Azerbaijani Manat',
            'BAM' => 'Bosnia & Herzegovina Convertible Mark',
            'BBD' => 'Barbadian Dollar',
            'BDT' => 'Bangladeshi Taka',
            'BIF' => 'Burundian Franc',
            'BGN' => 'Bulgarian Lev',
            'BMD' => 'Bermudian Dollar',
            'BND' => 'Brunei Dollar',
            'BOB' => 'Bolivian Boliviano',
            'BRL' => 'Brazilian Real',
            'BSD' => 'Bahamian Dollar',
            'BWP' => 'Botswana Pula',
            'BZD' => 'Belize Dollar',
            'CAD' => 'Canadian Dollar',
            'CDF' => 'Congolese Franc',
            'CHF' => 'Swiss Franc',
            'CLP' => 'Chilean Peso',
            'CNY' => 'Chinese Renminbi Yuan',
            'COP' => 'Colombian Peso',
            'CRC' => 'Costa Rican Colón',
            'CVE' => 'Cape Verdean Escudo',
            'CZK' => 'Czech Koruna',
            'DJF' => 'Djiboutian Franc',
            'DKK' => 'Danish Krone',
            'DOP' => 'Dominican Peso',
            'DZD' => 'Algerian Dinar',
            'EGP' => 'Egyptian Pound',
            'ETB' => 'Ethiopian Birr',
            'EUR' => 'Euro',
            'FJD' => 'Fijian Dollar',
            'FKP' => 'Falkland Islands Pound',
            'GBP' => 'British Pound',
            'GEL' => 'Georgian Lari',
            'GHS' => 'Ghanaian Cedi',
            'GIP' => 'Gibraltar Pound',
            'GMD' => 'Gambian Dalasi',
            'GNF' => 'Guinean Franc',
            'GTQ' => 'Guatemalan Quetzal',
            'GYD' => 'Guyanese Dollar',
            'HKD' => 'Hong Kong Dollar',
            'HNL' => 'Honduran Lempira',
            'HRK' => 'Croatian Kuna',
            'HTG' => 'Haitian Gourde',
            'HUF' => 'Hungarian Forint',
            'IDR' => 'Indonesian Rupiah',
            'ILS' => 'Israeli New Sheqel',
            'INR' => 'Indian Rupee',
            'ISK' => 'Icelandic Króna',
            'JMD' => 'Jamaican Dollar',
            'JPY' => 'Japanese Yen',
            'KES' => 'Kenyan Shilling',
            'KGS' => 'Kyrgyzstani Som',
            'KHR' => 'Cambodian Riel',
            'KMF' => 'Comorian Franc',
            'KRW' => 'South Korean Won',
            'KYD' => 'Cayman Islands Dollar',
            'KZT' => 'Kazakhstani Tenge',
            'LAK' => 'Lao Kip',
            'LBP' => 'Lebanese Pound',
            'LKR' => 'Sri Lankan Rupee',
            'LRD' => 'Liberian Dollar',
            'LSL' => 'Lesotho Loti',
            'MAD' => 'Moroccan Dirham',
            'MDL' => 'Moldovan Leu',
            'MGA' => 'Malagasy Ariary',
            'MKD' => 'Macedonian Denar',
            'MNT' => 'Mongolian Tögrög',
            'MOP' => 'Macanese Pataca',
            'MRO' => 'Mauritanian Ouguiya',
            'MUR' => 'Mauritian Rupee',
            'MVR' => 'Maldivian Rufiyaa',
            'MWK' => 'Malawian Kwacha',
            'MXN' => 'Mexican Peso',
            'MYR' => 'Malaysian Ringgit',
            'MZN' => 'Mozambican Metical',
            'NAD' => 'Namibian Dollar',
            'NGN' => 'Nigerian Naira',
            'NIO' => 'Nicaraguan Córdoba',
            'NOK' => 'Norwegian Krone',
            'NPR' => 'Nepalese Rupee',
            'NZD' => 'New Zealand Dollar',
            'PAB' => 'Panamanian Balboa',
            'PEN' => 'Peruvian Nuevo Sol',
            'PGK' => 'Papua New Guinean Kina',
            'PHP' => 'Philippine Peso',
            'PKR' => 'Pakistani Rupee',
            'PLN' => 'Polish Złoty',
            'PYG' => 'Paraguayan Guaraní',
            'QAR' => 'Qatari Riyal',
            'RON' => 'Romanian Leu',
            'RSD' => 'Serbian Dinar',
            'RUB' => 'Russian Ruble',
            'RWF' => 'Rwandan Franc',
            'SAR' => 'Saudi Riyal',
            'SBD' => 'Solomon Islands Dollar',
            'SCR' => 'Seychellois Rupee',
            'SEK' => 'Swedish Krona',
            'SGD' => 'Singapore Dollar',
            'SHP' => 'Saint Helenian Pound',
            'SLL' => 'Sierra Leonean Leone',
            'SOS' => 'Somali Shilling',
            'SRD' => 'Surinamese Dollar',
            'STD' => 'São Tomé and Príncipe Dobra',
            'SVC' => 'Salvadoran Colón',
            'SZL' => 'Swazi Lilangeni',
            'THB' => 'Thai Baht',
            'TJS' => 'Tajikistani Somoni',
            'TOP' => 'Tongan Paʻanga',
            'TRY' => 'Turkish Lira',
            'TTD' => 'Trinidad and Tobago Dollar',
            'TWD' => 'New Taiwan Dollar',
            'TZS' => 'Tanzanian Shilling',
            'UAH' => 'Ukrainian Hryvnia',
            'UGX' => 'Ugandan Shilling',
            'USD' => 'United States Dollar',
            'UYU' => 'Uruguayan Peso',
            'UZS' => 'Uzbekistani Som',
            'VND' => 'Vietnamese Đồng',
            'VUV' => 'Vanuatu Vatu',
            'WST' => 'Samoan Tala',
            'XAF' => 'Central African Cfa Franc',
            'XCD' => 'East Caribbean Dollar',
            'XOF' => 'West African Cfa Franc',
            'XPF' => 'Cfp Franc',
            'YER' => 'Yemeni Rial',
            'ZAR' => 'South African Rand',
            'ZMW' => 'Zambian Kwacha',
        ];

        return apply_filters('exh_donate_currencies', $currencies);
    }

    public static function getCurrencySymbol($currency)
    {
        $symbols = [
            'AED' => 'د.إ',                              // United Arab Emirates Dirham
            'AFN' => '؋',                                // Afghan Afghani
            'ALL' => 'L',                                // Albanian Lek
            'AMD' => '֏',                                // Armenian Dram
            'ANG' => 'ƒ',                                // Netherlands Antillean Gulden
            'AOA' => 'Kz',                               // Angolan Kwanza
            'ARS' => '$',                                // Argentine Peso
            'AUD' => '$',                                // Australian Dollar
            'AWG' => 'ƒ',                                // Aruban Florin
            'AZN' => '₼',                                // Azerbaijani Manat
            'BAM' => 'КМ',                               // Bosnia & Herzegovina Convertible Mark
            'BBD' => '$',                                // Barbadian Dollar
            'BDT' => '৳',                               // Bangladeshi Taka
            'BIF' => 'Fr',                               // Burundian Franc
            'BGN' => 'лв',                               // Bulgarian Lev
            'BMD' => '$',                                // Bermudian Dollar
            'BND' => '$',                                // Brunei Dollar
            'BOB' => 'Bs.',                              // Bolivian Boliviano
            'BRL' => 'R$',                               // Brazilian Real
            'BSD' => '$',                                // Bahamian Dollar
            'BWP' => 'P',                                // Botswana Pula
            'BZD' => '$',                                // Belize Dollar
            'CAD' => '$',                                // Canadian Dollar
            'CDF' => 'Fr',                               // Congolese Franc
            'CHF' => 'Fr',                               // Swiss Franc
            'CLP' => '$',                                // Chilean Peso
            'CNY' => '¥',                                // Chinese Renminbi Yuan
            'COP' => '$',                                // Colombian Peso
            'CRC' => '₡',                                // Costa Rican Colón
            'CVE' => 'Esc',                              // Cape Verdean Escudo
            'CZK' => 'Kč',                               // Czech Koruna
            'DJF' => 'Fr',                               // Djiboutian Franc
            'DKK' => 'kr',                               // Danish Krone
            'DOP' => 'RD$',                              // Dominican Peso
            'DZD' => 'دج',                               // Algerian Dinar
            'EGP' => 'ج.م',                              // Egyptian Pound
            'ETB' => 'ብር',                              // Ethiopian Birr
            'EUR' => '€',                                // Euro
            'FJD' => '$',                                // Fijian Dollar
            'FKP' => '£',                                // Falkland Islands Pound
            'GBP' => '£',                                // British Pound
            'GEL' => '₾',                                // Georgian Lari
            'GHS' => '₵',                                // Ghanaian Cedi
            'GIP' => '£',                                // Gibraltar Pound
            'GMD' => 'D',                                // Gambian Dalasi
            'GNF' => 'Fr',                               // Guinean Franc
            'GTQ' => 'Q',                                // Guatemalan Quetzal
            'GYD' => '$',                                // Guyanese Dollar
            'HKD' => '$',                                // Hong Kong Dollar
            'HNL' => 'L',                                // Honduran Lempira
            'HRK' => 'kn',                               // Croatian Kuna
            'HTG' => 'G',                                // Haitian Gourde
            'HUF' => 'Ft',                               // Hungarian Forint
            'IDR' => 'Rp',                               // Indonesian Rupiah
            'ILS' => '₪',                                // Israeli New Sheqel
            'INR' => '₹',                                // Indian Rupee
            'ISK' => 'kr',                               // Icelandic Króna
            'JMD' => 'J$',                               // Jamaican Dollar
            'JPY' => '¥',                                // Japanese Yen
            'KES' => 'KSh',                              // Kenyan Shilling
            'KGS' => 'с',                                // Kyrgyzstani Som
            'KHR' => '៛',                                // Cambodian Riel
            'KMF' => 'Fr',                               // Comorian Franc
            'KRW' => '₩',                                // South Korean Won
            'KYD' => '$',                                // Cayman Islands Dollar
            'KZT' => '₸',                                // Kazakhstani Tenge
            'LAK' => '₭',                                // Lao Kip
            'LBP' => 'ل.ل',                              // Lebanese Pound
            'LKR' => 'Rs',                               // Sri Lankan Rupee
            'LRD' => '$',                                // Liberian Dollar
            'LSL' => 'L',                                // Lesotho Loti
            'MAD' => 'د.م.',                             // Moroccan Dirham
            'MDL' => 'L',                                // Moldovan Leu
            'MGA' => 'Ar',                               // Malagasy Ariary
            'MKD' => 'ден',                              // Macedonian Denar
            'MNT' => '₮',                                // Mongolian Tögrög
            'MOP' => 'P',                                // Macanese Pataca
            'MRO' => 'UM',                               // Mauritanian Ouguiya
            'MUR' => '₨',                                // Mauritian Rupee
            'MVR' => 'ރ.',                              // Maldivian Rufiyaa
            'MWK' => 'MK',                               // Malawian Kwacha
            'MXN' => '$',                                // Mexican Peso
            'MYR' => 'RM',                               // Malaysian Ringgit
            'MZN' => 'MT',                               // Mozambican Metical
            'NAD' => '$',                                // Namibian Dollar
            'NGN' => '₦',                                // Nigerian Naira
            'NIO' => 'C$',                               // Nicaraguan Córdoba
            'NOK' => 'kr',                               // Norwegian Krone
            'NPR' => 'रू',                              // Nepalese Rupee
            'NZD' => '$',                                // New Zealand Dollar
            'PAB' => 'B/.',                              // Panamanian Balboa
            'PEN' => 'S/',                               // Peruvian Nuevo Sol
            'PGK' => 'K',                                // Papua New Guinean Kina
            'PHP' => '₱',                                // Philippine Peso
            'PKR' => '₨',                                // Pakistani Rupee
            'PLN' => 'zł',                               // Polish Złoty
            'PYG' => '₲',                                // Paraguayan Guaraní
            'QAR' => 'ر.ق',                              // Qatari Riyal
            'RON' => 'lei',                              // Romanian Leu
            'RSD' => 'дин.',                             // Serbian Dinar
            'RUB' => '₽',                                // Russian Ruble
            'RWF' => 'Fr',                               // Rwandan Franc
            'SAR' => 'ر.س',                              // Saudi Riyal
            'SBD' => '$',                                // Solomon Islands Dollar
            'SCR' => '₨',                                // Seychellois Rupee
            'SEK' => 'kr',                               // Swedish Krona
            'SGD' => '$',                                // Singapore Dollar
            'SHP' => '£',                                // Saint Helenian Pound
            'SLL' => 'Le',                               // Sierra Leonean Leone
            'SOS' => 'Sh',                               // Somali Shilling
            'SRD' => '$',                                // Surinamese Dollar
            'STD' => 'Db',                               // São Tomé and Príncipe Dobra
            'SVC' => '$',                                // Salvadoran Colón
            'SZL' => 'L',                                // Swazi Lilangeni
            'THB' => '฿',                                // Thai Baht
            'TJS' => 'ЅМ',                               // Tajikistani Somoni
            'TOP' => 'T$',                               // Tongan Paʻanga
            'TRY' => '₺',                                // Turkish Lira
            'TTD' => 'TT$',                              // Trinidad and Tobago Dollar
            'TWD' => 'NT$',                              // New Taiwan Dollar
            'TZS' => 'Sh',                               // Tanzanian Shilling
            'UAH' => '₴',                                // Ukrainian Hryvnia
            'UGX' => 'USh',                              // Ugandan Shilling
            'USD' => '$',                                // United States Dollar
            'UYU' => '$U',                               // Uruguayan Peso
            'UZS' => 'сўм',                              // Uzbekistani Som
            'VND' => '₫',                                // Vietnamese Đồng
            'VUV' => 'VT',                               // Vanuatu Vatu
            'WST' => 'T',                                // Samoan Tala
            'XAF' => 'Fr',                               // Central African Cfa Franc
            'XCD' => '$',                                // East Caribbean Dollar
            'XOF' => 'Fr',                               // West African Cfa Franc
            'XPF' => 'Fr',                               // Cfp Franc
            'YER' => '﷼',                               // Yemeni Rial
            'ZAR' => 'R',                                // South African Rand
            'ZMW' => 'ZK',                               // Zambian Kwacha
        ];

        return $symbols;
    }
}